version: "3.8"
services:
  vault:
    container_name: vault
    image: vassilij1/vault:1.15.6
    restart: unless-stopped
    ports:
      - 8200:8200
    volumes:
      - ./vault/config.hcl:/etc/vault/config.hcl
      - ./vault/data:/etc/vault/data
    networks:
      - proxy
networks:
  proxy:
    external: true
